### ISSUE TITLE
No Results Ubuntu

### ISSUE THREAD

**Issue by frozen-cdn** [aardwolfsecurityltd/SubSmash#1]
Was seeking a tool like this, chose a domain that absolutely has minimum two subdomains that were included in the default word list, but the program ran to completion and reported zero results found.

**Comment by aardwolfsecurityltd** [comment]
I think the issue could be the target web server rate limiting the tool which was leading to false negatives, we've updated the script to detect and respond to rate limiting. Hope this resolves the issue
